[package]
name = "pysearch"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev]
overflow-checks = false

[features]
simd = []

[dependencies]
rayon = "1.7.0"
dashmap = { version = "5.4.0", features = ["rayon"] }

# Doesn't seem to help much:
# [profile.release]
# lto = true
